// <auto-generated />
using System;
using UniFlowHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UniFlowHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514173511_SyncPerfisSistemaSnapshot")]
    partial class SyncPerfisSistemaSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjUnidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportadoPorUserId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("CartaoPontoArquivo");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoPontoArquivoId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConfirmadoPeloUsuario")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRespostaUsuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FuncionarioNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioEditado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinhaOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrecisaAjuste")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartaoPontoArquivoId");

                    b.HasIndex("EditadoPorUserId");

                    b.ToTable("CartaoPontoRegistro");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ChamadoTIId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoTIId");

                    b.ToTable("ChamadoTIComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcessoRemotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnexoImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrimeiroEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataReabertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoSistemaOperacional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Reaberto")
                        .HasColumnType("boolean");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskServidor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("integer");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("ChamadoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaRetorno")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patrimonio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("EquipamentoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GuiaIcmsPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuiaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("GuiaId")
                        .IsUnique();

                    b.ToTable("GuiaIcmsPagamento");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PecaVendedorMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CpfVendedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeVendedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("CpfVendedor")
                        .IsUnique();

                    b.ToTable("PecaVendedorMeta");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PerfilSistema");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilSistemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilSistemaId", "Chave")
                        .IsUnique();

                    b.ToTable("PerfilSistemaAcesso");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aprovador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEnvioCompras")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FornecedorSugerido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesCompras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoCompra");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitacaoCompraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoCompraId");

                    b.ToTable("SolicitacaoCompraComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitacaoRHId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoRHId");

                    b.ToTable("SolicitacaoRHComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexossUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("integer");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoRH");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroRevenda")
                        .HasColumnType("integer");

                    b.Property<string>("Revenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskHostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskSenha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RustDeskSistemaOperacional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.VeiculoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Reservado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.ToTable("VeiculoReserva");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "ImportadoPorUser")
                        .WithMany()
                        .HasForeignKey("ImportadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportadoPorUser");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoRegistro", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.CartaoPontoArquivo", "Arquivo")
                        .WithMany("Registros")
                        .HasForeignKey("CartaoPontoArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.Users", "EditadoPorUser")
                        .WithMany()
                        .HasForeignKey("EditadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arquivo");

                    b.Navigation("EditadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.ChamadosTI", "ChamadoTI")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("ChamadoTIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChamadoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GuiaIcmsPagamento", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PecaVendedorMeta", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaAcesso", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.PerfilSistema", "PerfilSistema")
                        .WithMany("Acessos")
                        .HasForeignKey("PerfilSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilSistema");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.SolicitacaoCompra", "SolicitacaoCompra")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoCompra");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.SolicitacoesRH", "SolicitacaoRH")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoRHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoRH");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Empresa", "EmpresaCadastro")
                        .WithMany("Revendas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmpresaCadastro");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.VeiculoReserva", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Empresa", b =>
                {
                    b.Navigation("Revendas");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistema", b =>
                {
                    b.Navigation("Acessos");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.Navigation("CreatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
