using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UniFlowHub.Migrations
{
    /// <inheritdoc />
    public partial class SyncPerfilEmpresaSnapshot : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS "IX_PecaVendedorMeta_CpfVendedor";
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_PecaVendedorMeta_CpfVendedor"
                ON "PecaVendedorMeta" ("CpfVendedor");
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "PerfilSistemaEmpresa" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PerfilSistemaId" integer NOT NULL,
                    "EmpresaNumero" integer NOT NULL,
                    CONSTRAINT "PK_PerfilSistemaEmpresa" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'FK_PerfilSistemaEmpresa_PerfilSistema_PerfilSistemaId'
                    ) THEN
                        ALTER TABLE "PerfilSistemaEmpresa"
                        ADD CONSTRAINT "FK_PerfilSistemaEmpresa_PerfilSistema_PerfilSistemaId"
                        FOREIGN KEY ("PerfilSistemaId") REFERENCES "PerfilSistema" ("Id") ON DELETE CASCADE;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_PerfilSistemaEmpresa_PerfilSistemaId_EmpresaNumero"
                ON "PerfilSistemaEmpresa" ("PerfilSistemaId", "EmpresaNumero");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
