// <auto-generated />
using System;
using DRFlowHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DRFlowHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507194930_AddChamadoTIHistoricoReabertura")]
    partial class AddChamadoTIHistoricoReabertura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DRFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamadoTIId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoTIId");

                    b.ToTable("ChamadoTIComunicacao");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcessoRemotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnexoImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPrimeiroEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataReabertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reaberto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("ChamadoTI");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPrevistaRetorno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patrimonio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("EquipamentoTI");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aprovador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEnvioCompras")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FornecedorSugerido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesCompras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoCompra");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitacaoCompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoCompraId");

                    b.ToTable("SolicitacaoCompraComunicacao");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitacaoRHId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoRHId");

                    b.ToTable("SolicitacaoRHComunicacao");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnexossUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoRH");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.ChamadosTI", "ChamadoTI")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("ChamadoTIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChamadoTI");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.SolicitacaoCompra", "SolicitacaoCompra")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoCompra");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.SolicitacoesRH", "SolicitacaoRH")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoRHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoRH");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.Users", b =>
                {
                    b.HasOne("DRFlowHub.Api.Models.Users", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DRFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.Unidade", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DRFlowHub.Api.Models.Users", b =>
                {
                    b.Navigation("CreatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
